"""add_oems_and_position

Revision ID: ccba4fdef797
Revises: 0002
Create Date: 2026-06-19 13:09:06.080505
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ccba4fdef797'
down_revision: Union[str, None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('positions',
    sa.Column('symbol', sa.String(length=40), nullable=False),
    sa.Column('exchange', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('average_price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('stop_loss', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('take_profit', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('trailing_stop_loss_pct', sa.Float(), nullable=True),
    sa.Column('trailing_stop_loss_trigger', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('highest_price', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_positions'))
    )
    op.create_index(op.f('ix_positions_status'), 'positions', ['status'], unique=False)
    op.create_index(op.f('ix_positions_symbol'), 'positions', ['symbol'], unique=True)
    op.drop_index('ix_memory_embeddings_embedding', table_name='memory_embeddings', postgresql_using='hnsw')
    op.add_column('orders', sa.Column('price', sa.Numeric(precision=18, scale=2), nullable=True))
    op.add_column('orders', sa.Column('stop_loss', sa.Numeric(precision=18, scale=2), nullable=True))
    op.add_column('orders', sa.Column('take_profit', sa.Numeric(precision=18, scale=2), nullable=True))
    op.add_column('orders', sa.Column('trailing_stop_loss_pct', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('trailing_stop_loss_trigger', sa.Numeric(precision=18, scale=2), nullable=True))
    op.add_column('orders', sa.Column('parent_order_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_orders_parent_order_id'), 'orders', ['parent_order_id'], unique=False)
    op.create_foreign_key(op.f('fk_orders_parent_order_id_orders'), 'orders', 'orders', ['parent_order_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_orders_parent_order_id_orders'), 'orders', type_='foreignkey')
    op.drop_index(op.f('ix_orders_parent_order_id'), table_name='orders')
    op.drop_column('orders', 'parent_order_id')
    op.drop_column('orders', 'trailing_stop_loss_trigger')
    op.drop_column('orders', 'trailing_stop_loss_pct')
    op.drop_column('orders', 'take_profit')
    op.drop_column('orders', 'stop_loss')
    op.drop_column('orders', 'price')
    op.create_index('ix_memory_embeddings_embedding', 'memory_embeddings', ['embedding'], unique=False, postgresql_using='hnsw')
    op.drop_index(op.f('ix_positions_symbol'), table_name='positions')
    op.drop_index(op.f('ix_positions_status'), table_name='positions')
    op.drop_table('positions')
    # ### end Alembic commands ###
